apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  namespace: petclinic
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: shubh010701/petclinic:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_URL
          valueFrom:
            configMapKeyRef:
              name: petclinic-config
              key: MYSQL_URL
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: petclinic-secret
              key: MYSQL_PASSWORD

      

